source 'https://github.com/CocoaPods/Specs.git'

target 'AcmePush', :exclusive => true do
  pod "Qwasi", :path => "../"
end

target 'Qwasi_Tests', :exclusive => true do
  use_frameworks!
  pod "Qwasi", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
