source 'https://github.com/CocoaPods/Specs.git'
source 'https://code.qwasi.com/scm/osrc/pods.git'

target 'AcmePush', :exclusive => true do
  pod "Qwasi", :path => "../"
end

target 'Qwasi_Tests', :exclusive => true do
  pod "Qwasi", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
