source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Qwasi_Example', :exclusive => true do
  pod "Qwasi", :path => "../"
end

target 'Qwasi_Tests', :exclusive => true do
  pod "Qwasi", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
